version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: zaag_db
      POSTGRES_USER: zaag_user
      POSTGRES_PASSWORD: zaag_pass
